# b17: GRRAT · ΔΣ=42
"""Pins `scripts/check_ratification.py` (Grove v0.9 PR 12).

INVARIANTS.md §12 (ratification) and §10 (CI proves the invariants).
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "scripts" / "check_ratification.py"


def _run(body: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--body", body],
        capture_output=True,
        text=True,
        check=False,
    )


def _run_event(event: dict, tmp_path: Path) -> subprocess.CompletedProcess:
    """Run the checker driven by a synthetic GITHUB_EVENT_PATH payload.

    Everything about how CI exercises this script routes through the
    event file; the local `--body` path is a testing convenience. The
    release-please exemption reads `pull_request.user.login` and
    `pull_request.head.ref`, which are only carried in the event JSON,
    so it can only be pinned this way.
    """
    event_path = tmp_path / "event.json"
    event_path.write_text(json.dumps(event), encoding="utf-8")
    env = os.environ.copy()
    env["GITHUB_EVENT_PATH"] = str(event_path)
    # stdin as a fallback body source would eclipse the event; force
    # the checker's isatty branch by opening a pty-less pipe with no data
    # via /dev/null on the parent's stdin.
    return subprocess.run(
        [sys.executable, str(SCRIPT)],
        capture_output=True,
        text=True,
        check=False,
        env=env,
        stdin=subprocess.DEVNULL,
    )


def test_clean_ratification_passes() -> None:
    """§12: the ratification line signs off at the BOTTOM of the body."""
    body = 'The PR body comes first.\n\nRatified-by: sean — "go ahead with §12"\n'
    r = _run(body)
    assert r.returncode == 0, r.stdout + r.stderr
    assert "clean" in r.stdout


def test_ratification_sits_below_the_agents_marks() -> None:
    """The human's sign-off goes last — beneath the work AND beneath the
    marks the agents left on it (§11 `Persona:` trailers, attribution
    footers). This is the shape every real PR body takes."""
    body = (
        "## What changed\n"
        "\n"
        "Some work.\n"
        "\n"
        "Persona: heimdallr\n"
        "\n"
        "Generated by Claude Code\n"
        "\n"
        'Ratified-by: sean — "get the piddle stuff done"\n'
    )
    r = _run(body)
    assert r.returncode == 0, r.stdout + r.stderr


def test_ascii_dash_variant_passes() -> None:
    body = 'Ratified-by: sean - "run it, keep the reorder"\n'
    r = _run(body)
    assert r.returncode == 0, r.stdout + r.stderr


def test_curly_quotes_variant_passes() -> None:
    body = "Ratified-by: sean — “go ahead with §12”\n"
    r = _run(body)
    assert r.returncode == 0, r.stdout + r.stderr


def test_missing_line_flagged() -> None:
    body = "Just a PR description with no ratification line.\n"
    r = _run(body)
    assert r.returncode == 1, r.stdout + r.stderr
    assert "does not match" in r.stderr


def test_empty_body_flagged() -> None:
    r = _run("")
    assert r.returncode == 1, r.stdout + r.stderr
    assert "empty" in r.stderr


def test_ratification_above_other_lines_flagged() -> None:
    """A line at the top is no longer the shape §12 asks for. Position is
    load-bearing: without it, any `Ratified-by:` mentioned in passing
    anywhere in a long body would satisfy the check."""
    body = 'Ratified-by: sean — "go"\n\nSummary of the changes.\n'
    r = _run(body)
    assert r.returncode == 1, r.stdout + r.stderr


def test_ratification_buried_mid_body_flagged() -> None:
    """Neither first nor last — a quote cited mid-discussion is not a
    sign-off, and must not read as one."""
    body = (
        "Here is what changed.\n"
        "\n"
        'Ratified-by: sean — "go"\n'
        "\n"
        "...and some trailing discussion after it.\n"
    )
    r = _run(body)
    assert r.returncode == 1, r.stdout + r.stderr


def test_tool_appended_footer_below_the_line_passes() -> None:
    """Some tooling appends its own attribution footer to a PR body
    server-side, after the author's text — no author can place a line
    beneath it. This is the shape GitHub actually stored for Grove PR 8,
    and the reason the check went red on a body that was correct.
    """
    body = (
        "Description of the change.\n"
        "\n"
        "Persona: heimdallr\n"
        "\n"
        "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n"
        "\n"
        "https://claude.ai/code/session_01TfZLArksQMHhhCni2ZjRZV\n"
        "\n"
        'Ratified-by: sean — "please pr"\n'
        "\n"
        "---\n"
        "_Generated by [Claude Code](https://claude.ai/code/session_01TfZ)_\n"
    )
    r = _run(body)
    assert r.returncode == 0, r.stdout + r.stderr


def test_cursor_made_with_footer_skipped() -> None:
    """Cursor appends 'Made with [Cursor](…)' after the author's text —
    same class as the Claude Code attribution footer, and the reason
    willows-grove #37 went red on an otherwise correct body."""
    body = (
        "Description of the change.\n"
        "\n"
        'Ratified-by: sean-campbell — "Implement the plan as specified"\n'
        "\n"
        "Made with [Cursor](https://cursor.com)\n"
    )
    r = _run(body)
    assert r.returncode == 0, r.stdout + r.stderr


def test_real_content_below_the_line_still_flagged() -> None:
    """The footer skip is an allowlist, not a general 'ignore trailing
    junk'. Prose after the sign-off means the sign-off was not last, and
    that must still fail — otherwise the position requirement is gone and
    a `Ratified-by:` quoted in passing passes for authorization.
    """
    body = (
        "Description.\n"
        "\n"
        'Ratified-by: sean — "go"\n'
        "\n"
        "---\n"
        "_Generated by [Claude Code](https://claude.ai/code/session_01TfZ)_\n"
        "\n"
        "PS: one more thought about the design.\n"
    )
    r = _run(body)
    assert r.returncode == 1, r.stdout + r.stderr


def test_footer_alone_without_a_ratification_line_flagged() -> None:
    """Skipping the footer must not skip its way into a pass on a body
    that never carried a ratification line at all."""
    body = (
        "Description with no authorization.\n"
        "\n"
        "---\n"
        "_Generated by [Claude Code](https://claude.ai/code/session_01TfZ)_\n"
    )
    r = _run(body)
    assert r.returncode == 1, r.stdout + r.stderr


def test_no_quote_flagged() -> None:
    body = "Ratified-by: sean — go ahead\n"
    r = _run(body)
    assert r.returncode == 1, r.stdout + r.stderr


def test_empty_identifier_flagged() -> None:
    body = 'Ratified-by:  — "go"\n'
    r = _run(body)
    assert r.returncode == 1, r.stdout + r.stderr


# ── release-please bounded exemption (PR 78) ─────────────────────────────────
#
# release-please writes its release PR's body itself, so it cannot carry
# the operator's verbatim words by construction. Ratification of the
# release ships one level up: the operator's merge click and the tag
# push that `release.yml` publishes on. The exemption is bounded on TWO
# axes at once (author login AND head-ref prefix). The plants below
# prove both directions.


def _release_please_event(
    *,
    body: str = "",
    user_login: str = "willow-ci[bot]",
    head_ref: str = "release-please--branches--master--components--willows-grove",
) -> dict:
    return {
        "pull_request": {
            "body": body,
            "user": {"login": user_login},
            "head": {"ref": head_ref},
        }
    }


def test_release_please_pr_exempt_even_with_no_ratification(tmp_path: Path) -> None:
    """The exact shape release-please cuts: no `Ratified-by:` line
    anywhere in the body (release-please writes the body itself), and
    the check clears it. This is the failing case #75 reported."""
    body = (
        ":robot: I have created a release *beep* *boop*\n"
        "---\n\n\n"
        "## [0.11.0](https://github.com/... /compare/v0.10.0...v0.11.0) (2026-09-19)\n"
        "\n"
        "### Added\n"
        "\n"
        "* **deploy:** track the Kart mount policy...\n"
        "\n---\n"
        "This PR was generated with [Release Please](...).\n"
    )
    event = _release_please_event(body=body)
    r = _run_event(event, tmp_path)
    assert r.returncode == 0, r.stdout + r.stderr
    assert "release-please PR exempt" in r.stdout


def test_release_please_matching_login_wrong_head_ref_still_fails(
    tmp_path: Path,
) -> None:
    """Login-only match: a human might in theory push a `willow-ci[bot]`
    author, or the App might open a non-release PR in the future. Either
    way, a PR not on a `release-please--` branch still owes §12 its
    signature."""
    event = _release_please_event(
        body="A PR the bot opened for some other reason.\n",
        head_ref="feat/something-else",
    )
    r = _run_event(event, tmp_path)
    assert r.returncode == 1, r.stdout + r.stderr


def test_release_please_matching_head_ref_wrong_login_still_fails(
    tmp_path: Path,
) -> None:
    """Head-ref-only match: the branch name isn't reserved by GitHub;
    anyone could push a `release-please--*` branch. A PR from a non-bot
    author on such a branch is still an ordinary PR and must ratify."""
    event = _release_please_event(
        body="A human pretending to be release-please.\n",
        user_login="rudi193-cmd",
    )
    r = _run_event(event, tmp_path)
    assert r.returncode == 1, r.stdout + r.stderr


def test_release_please_head_ref_prefix_close_but_not_matching_still_fails(
    tmp_path: Path,
) -> None:
    """`release-please-manual` is not release-please's own pattern (it
    creates `release-please--*` with two dashes). A single-dash lookalike
    must not ride the exemption in."""
    event = _release_please_event(
        body="A branch pretending to be a release cut.\n",
        head_ref="release-please-manual-cut",
    )
    r = _run_event(event, tmp_path)
    assert r.returncode == 1, r.stdout + r.stderr
