#!/usr/bin/env python3
"""
grove_docs_extract — Grove messages → enterprise doc artifacts (digests, candidates).
b17: GDOCX  ΔΣ=42

Reads Postgres directly (psycopg2). DSN: WILLOW_DB_URL or WILLOW_PG_DB + WILLOW_PG_USER.
See docs/extractor/GROVE_DOCS_EXTRACTOR_SPEC.md.
"""
from __future__ import annotations

import argparse
import fnmatch
import os
import re
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path

try:
    import psycopg2
    import psycopg2.extras
except ImportError:  # pragma: no cover
    print("grove_docs_extract: install psycopg2-binary", file=sys.stderr)
    raise SystemExit(1) from None


# --- Heuristics (see GROVE_DOCS_EXTRACTOR_SPEC.md) ---

ADR_RE = re.compile(
    r"(?i)(\[decision\]|\[adr\]|ratified|needs decision|alternatives considered|\badr\b|"
    r"spec ratified|sequence|needs a decision)"
)
INCIDENT_RE = re.compile(
    r"(?i)(\[incident\]|\[runbook\]|pool exhaustion|deadlock|down\b|locks?\b|"
    r"postgres|auth failure|oauth|pg_notify|connection refused|timeout)"
)
TAG_PREFIX = re.compile(
    r"^\s*(\[DECISION\]|\[ADR\]|\[INCIDENT\]|\[RUNBOOK\]|\[SCHEMA\]|\[GAP\])",
    re.I,
)


@dataclass
class Row:
    mid: int
    created_at: datetime
    channel: str
    sender: str
    content: str

    def excerpt(self, n: int = 240) -> str:
        one = " ".join(self.content.split())
        if len(one) <= n:
            return one
        return one[: n - 1] + "…"


def get_dsn() -> str:
    dsn = os.getenv("WILLOW_DB_URL", "")
    if dsn:
        return dsn
    pg_db = os.getenv("WILLOW_PG_DB", "willow_19")
    pg_user = os.getenv("WILLOW_PG_USER", os.environ.get("USER", ""))
    return f"dbname={pg_db} user={pg_user}"


def connect():
    conn = psycopg2.connect(get_dsn())
    conn.autocommit = True
    cur = conn.cursor()
    cur.execute("SET search_path = grove, public")
    cur.close()
    return conn


def fetch_messages(
    conn,
    *,
    limit: int,
    since: datetime | None,
    until: datetime | None,
    channels: Sequence[str] | None,
    channel_glob: str | None,
    include_deleted: bool,
) -> list[Row]:
    cond = ["1=1"]
    params: list = []
    if not include_deleted:
        cond.append("m.is_deleted = 0")
    if since:
        cond.append("m.created_at >= %s")
        params.append(since)
    if until:
        cond.append("m.created_at <= %s")
        params.append(until)
    if channels:
        cond.append("c.name = ANY(%s)")
        params.append(list(channels))
    where = " AND ".join(cond)
    sql = f"""
        SELECT m.id, m.created_at, c.name, m.sender, m.content
        FROM grove.messages m
        JOIN grove.channels c ON c.id = m.channel_id
        WHERE {where}
        ORDER BY m.id DESC
        LIMIT %s
    """
    params.append(limit)
    rows: list[Row] = []
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(sql, params)
        for r in cur.fetchall():
            row = Row(
                mid=r["id"],
                created_at=r["created_at"],
                channel=r["name"],
                sender=r["sender"],
                content=r["content"] or "",
            )
            if channel_glob and not fnmatch.fnmatch(row.channel, channel_glob):
                continue
            rows.append(row)
    return rows


def parse_iso_dt(s: str | None) -> datetime | None:
    if not s:
        return None
    if re.match(r"^\d{4}-\d{2}-\d{2}$", s):
        return datetime.fromisoformat(s + "T00:00:00+00:00").astimezone(timezone.utc)
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def write_digest(out: Path, rows: list[Row], meta: str) -> Path:
    out.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()
    path = out / f"digest-{today}.md"
    lines = [
        f"# Grove digest ({today})",
        "",
        f"_Generated by `grove_docs_extract.py`. {meta}_",
        "",
        "| id | created_at | channel | sender | excerpt |",
        "|---:|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda x: x.mid, reverse=True):
        ts = r.created_at.isoformat() if r.created_at else ""
        ex = r.excerpt().replace("|", "\\|")
        lines.append(f"| {r.mid} | {ts} | {r.channel} | {r.sender} | {ex} |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def filter_adr(rows: list[Row]) -> list[Row]:
    out = []
    for r in rows:
        if ADR_RE.search(r.content) or TAG_PREFIX.search(r.content):
            out.append(r)
    return out


def filter_incident(rows: list[Row]) -> list[Row]:
    out = []
    for r in rows:
        if INCIDENT_RE.search(r.content) or TAG_PREFIX.search(r.content):
            out.append(r)
    return out


def write_candidates(
    out: Path,
    adr_rows: list[Row],
    inc_rows: list[Row],
    meta: str,
) -> tuple[Path, Path]:
    out.mkdir(parents=True, exist_ok=True)
    adr_p = out / "adr-candidates.md"
    inc_p = out / "incident-candidates.md"

    def render(title: str, rs: list[Row]) -> str:
        lines = [
            f"# {title}",
            "",
            f"_Generated by `grove_docs_extract.py`. {meta}_",
            "",
            "Refs-not-blobs: use `grove.messages.id` to pull full text from Postgres when promoting to ADRs/runbooks.",
            "",
            "| message id | channel | sender | receipt excerpt |",
            "|---:|---|---|---|",
        ]
        for r in sorted(rs, key=lambda x: x.mid, reverse=True):
            ex = r.excerpt(200).replace("|", "\\|")
            lines.append(f"| {r.mid} | {r.channel} | {r.sender} | {ex} |")
        return "\n".join(lines) + "\n"

    adr_p.write_text(render("ADR / decision candidates", adr_rows), encoding="utf-8")
    inc_p.write_text(render("Incident / runbook candidates", inc_rows), encoding="utf-8")
    return adr_p, inc_p


def write_adr_stubs(stub_dir: Path, rows: list[Row], limit: int) -> list[Path]:
    stub_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for r in sorted(rows, key=lambda x: x.mid, reverse=True)[:limit]:
        slug = re.sub(r"[^a-z0-9]+", "-", r.excerpt(40).lower()).strip("-")[:40] or "message"
        d = r.created_at.date().isoformat().replace("-", "")[:8]
        name = f"ADR-{d}-msg{r.mid}-{slug}.md"
        path = stub_dir / name
        body = "\n".join(
            [
                f"# ADR stub — message `{r.mid}`",
                "",
                "**Status:** draft (extracted stub — human must complete)",
                "",
                "## Decision",
                "",
                "<!-- one sentence -->",
                "",
                "## Context",
                "",
                "<!-- why -->",
                "",
                "## Alternatives considered",
                "",
                "- ",
                "",
                "## Consequences",
                "",
                "- ",
                "",
                "## Receipts",
                "",
                f"- Grove `grove.messages.id` = **{r.mid}** (channel `{r.channel}`, sender `{r.sender}`)",
                "",
            ]
        )
        path.write_text(body, encoding="utf-8")
        written.append(path)
    return written


def cmd_digest(args: argparse.Namespace) -> int:
    conn = connect()
    try:
        rows = fetch_messages(
            conn,
            limit=args.limit,
            since=args.since,
            until=args.until,
            channels=args.channels,
            channel_glob=args.channel_glob,
            include_deleted=args.include_deleted,
        )
        meta = f"limit={args.limit}, rows={len(rows)}"
        path = write_digest(Path(args.out), rows, meta)
        print(path)
        return 0
    finally:
        conn.close()


def cmd_candidates(args: argparse.Namespace) -> int:
    conn = connect()
    try:
        rows = fetch_messages(
            conn,
            limit=args.limit,
            since=args.since,
            until=args.until,
            channels=args.channels,
            channel_glob=args.channel_glob,
            include_deleted=args.include_deleted,
        )
        adr_rows = filter_adr(rows)
        inc_rows = filter_incident(rows)
        meta = f"scanned={len(rows)}, adr_hits={len(adr_rows)}, incident_hits={len(inc_rows)}"
        adr_p, inc_p = write_candidates(Path(args.out), adr_rows, inc_rows, meta)
        print(adr_p)
        print(inc_p)
        if args.stubs:
            stubs = write_adr_stubs(Path(args.stub_dir), adr_rows, args.stub_limit)
            for p in stubs:
                print(p)
        return 0
    finally:
        conn.close()


def cmd_all(args: argparse.Namespace) -> int:
    conn = connect()
    try:
        rows = fetch_messages(
            conn,
            limit=args.limit,
            since=args.since,
            until=args.until,
            channels=args.channels,
            channel_glob=args.channel_glob,
            include_deleted=args.include_deleted,
        )
        adr_rows = filter_adr(rows)
        inc_rows = filter_incident(rows)
        meta = f"scanned={len(rows)}, adr_hits={len(adr_rows)}, incident_hits={len(inc_rows)}"
        dpath = write_digest(Path(args.out), rows, meta)
        adr_p, inc_p = write_candidates(Path(args.out), adr_rows, inc_rows, meta)
        print(dpath)
        print(adr_p)
        print(inc_p)
        if args.stubs:
            stubs = write_adr_stubs(Path(args.stub_dir), adr_rows, args.stub_limit)
            for p in stubs:
                print(p)
        return 0
    finally:
        conn.close()


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Grove → docs extractor",
        epilog="Global flags (--limit, --out, …) must appear **before** the subcommand "
        "(example: `%(prog)s --limit 5000 all`).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--out",
        default="docs/generated",
        help="Output directory (default: docs/generated)",
    )
    p.add_argument("--limit", type=int, default=10_000, help="Max messages (default 10000)")
    p.add_argument("--since", help="ISO date/datetime lower bound (optional)")
    p.add_argument("--until", help="ISO date/datetime upper bound (optional)")
    p.add_argument(
        "--channels",
        help="Comma-separated channel names to include (exact match)",
    )
    p.add_argument(
        "--channel-glob",
        dest="channel_glob",
        help="Glob filter on channel name applied after SQL fetch (optional)",
    )
    p.add_argument(
        "--include-deleted",
        action="store_true",
        help="Include soft-deleted messages",
    )
    p.add_argument(
        "--stubs",
        action="store_true",
        help="Write ADR stub files for top matches (candidates/all)",
    )
    p.add_argument(
        "--stub-dir",
        default="docs/adrs/_generated_stubs",
        help="Directory for ADR stubs",
    )
    p.add_argument("--stub-limit", type=int, default=10, help="Max ADR stub files")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("digest", help="Write digest table only").set_defaults(func=cmd_digest)
    c = sub.add_parser("candidates", help="ADR + incident candidate lists")
    c.set_defaults(func=cmd_candidates)
    a = sub.add_parser("all", help="Digest + candidates")
    a.set_defaults(func=cmd_all)
    return p


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    p = build_parser()
    args = p.parse_args(argv)
    args.since = parse_iso_dt(args.since) if getattr(args, "since", None) else None
    args.until = parse_iso_dt(args.until) if getattr(args, "until", None) else None
    ch = getattr(args, "channels", None)
    args.channels = [c.strip() for c in ch.split(",") if c.strip()] if ch else None
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
